## Linear Algebra with NumPy

In [6]:
# Linear Algebra with NumPy

import numpy as np

A = np.array([[1,2,3],
              [4,5,6]])

B = np.array([
    [7,8],
    [9,10],
    [11,12]
])


multiply = np.dot(A,B)
print(multiply)

[[ 58  64]
 [139 154]]


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b.shape)

In [2]:
np.sin(np.pi/2)

np.float64(1.0)

In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


In [4]:
a = np.array([3, 1, 2])
print(np.sort(a))

[1 2 3]


In [5]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication using np.dot()
result = np.dot(A, B)
print("np.dot(A, B) =")
print(result)

# Alternative method using @ operator
result2 = A @ B
print("\nA @ B =")
print(result2)

# Alternative method using np.matmul()
result3 = np.matmul(A, B)
print("\nnp.matmul(A, B) =")
print(result3)

np.dot(A, B) =
[[19 22]
 [43 50]]

A @ B =
[[19 22]
 [43 50]]

np.matmul(A, B) =
[[19 22]
 [43 50]]
