## ndarray Manipulation -1


In [1]:
import numpy as np 


In [2]:
arr = np.random.randint(1,100,size=(10,5))
print(arr)
print(arr.shape) # (10, 5)
print(arr.ndim)


[[ 9  9 15 11 33]
 [23 21 97 91  7]
 [43 76  5 25 59]
 [74 33 79 34 24]
 [82 56 35 81 43]
 [26 44 33 20 75]
 [31 84 26 42 31]
 [68 86 29 23 60]
 [29 23 44 84 73]
 [28 18  6 31  2]]
(10, 5)
2


In [3]:
arr1 = arr.reshape(5,10)
print(arr1) 
print(arr1.shape)

[[ 9  9 15 11 33 23 21 97 91  7]
 [43 76  5 25 59 74 33 79 34 24]
 [82 56 35 81 43 26 44 33 20 75]
 [31 84 26 42 31 68 86 29 23 60]
 [29 23 44 84 73 28 18  6 31  2]]
(5, 10)


In [4]:
arr2 = arr.flatten()
print(arr2) 
print(arr2.shape)
print(arr2.ndim)

[ 9  9 15 11 33 23 21 97 91  7 43 76  5 25 59 74 33 79 34 24 82 56 35 81
 43 26 44 33 20 75 31 84 26 42 31 68 86 29 23 60 29 23 44 84 73 28 18  6
 31  2]
(50,)
1


In [5]:
# coloumn wise flatening
arr3 = np.ravel(arr,order="F")
print(arr3) 
print(arr3.shape)
print(arr3.ndim)

[ 9 23 43 74 82 26 31 68 29 28  9 21 76 33 56 44 84 86 23 18 15 97  5 79
 35 33 26 29 44  6 11 91 25 34 81 20 42 23 84 31 33  7 59 24 43 75 31 60
 73  2]
(50,)
1


In [6]:
# row wise flatening
arr3 = np.ravel(arr,order="C")
print(arr3) 
print(arr3.shape)
print(arr3.ndim)

[ 9  9 15 11 33 23 21 97 91  7 43 76  5 25 59 74 33 79 34 24 82 56 35 81
 43 26 44 33 20 75 31 84 26 42 31 68 86 29 23 60 29 23 44 84 73 28 18  6
 31  2]
(50,)
1


In [7]:
a = np.random.randint(1,100,size=(10,5))
b = np.random.randint(100,10000,size=(10,5))


print(a)
print(b)

[[51 45 56 25 97]
 [70 87 98 97 95]
 [43 14 99 33 79]
 [55 46 12 75 42]
 [ 9  9 78 59 51]
 [ 3 75 95 93 41]
 [32 41  8  6 23]
 [61 16 28 25 57]
 [56 41 63 53  2]
 [34 54  9 68 78]]
[[7546 8102 7085 7019 2039]
 [2504 6840 8378 2819 7177]
 [8166 1737 1683 8718 9027]
 [8520 1704  759 5795 3335]
 [7020 5158 2957 6528 6767]
 [1752 1122 7418 7745 3017]
 [ 370 9300 6013 7520 3996]
 [7139 3695 2112 3513  854]
 [ 300 8334 6795  305 5359]
 [7929 6510  230 4547 2386]]


In [8]:
# concatenate 
# colum
c = np.concatenate((a,b),axis=0) # row wise
print(c)

[[  51   45   56   25   97]
 [  70   87   98   97   95]
 [  43   14   99   33   79]
 [  55   46   12   75   42]
 [   9    9   78   59   51]
 [   3   75   95   93   41]
 [  32   41    8    6   23]
 [  61   16   28   25   57]
 [  56   41   63   53    2]
 [  34   54    9   68   78]
 [7546 8102 7085 7019 2039]
 [2504 6840 8378 2819 7177]
 [8166 1737 1683 8718 9027]
 [8520 1704  759 5795 3335]
 [7020 5158 2957 6528 6767]
 [1752 1122 7418 7745 3017]
 [ 370 9300 6013 7520 3996]
 [7139 3695 2112 3513  854]
 [ 300 8334 6795  305 5359]
 [7929 6510  230 4547 2386]]


In [9]:
# concatenate 
# col
c = np.concatenate((a,b),axis=1) # col wise
print(c)

[[  51   45   56   25   97 7546 8102 7085 7019 2039]
 [  70   87   98   97   95 2504 6840 8378 2819 7177]
 [  43   14   99   33   79 8166 1737 1683 8718 9027]
 [  55   46   12   75   42 8520 1704  759 5795 3335]
 [   9    9   78   59   51 7020 5158 2957 6528 6767]
 [   3   75   95   93   41 1752 1122 7418 7745 3017]
 [  32   41    8    6   23  370 9300 6013 7520 3996]
 [  61   16   28   25   57 7139 3695 2112 3513  854]
 [  56   41   63   53    2  300 8334 6795  305 5359]
 [  34   54    9   68   78 7929 6510  230 4547 2386]]


## ndarray Manipulation -2

In [11]:

math = np.random.randint(1,100,size=(2,5))
science = np.random.randint(1,100,size=(2,5))

print(math)
print(science)

[[60 18 81 19 96]
 [21 82 73 13 23]]
[[27 60 63 25 27]
 [66 36 48 52 18]]


In [12]:
transpose = math.T

print(transpose)

[[60 21]
 [18 82]
 [81 73]
 [19 13]
 [96 23]]


In [19]:
# array split 
df = np.random.randint(1,100,size=(10,5))
print(df)

[[18 22 89  3 28]
 [42 54 99 65 97]
 [ 6  4 95 70 57]
 [12 84 29 58 86]
 [74 34 79 37 88]
 [52 96 15 45 62]
 [ 3  7 26 90 19]
 [17 25 93 89 67]
 [ 7  5 94 16 95]
 [83 95 33 46 10]]


In [20]:
data,dt2,dt3 = np.array_split(df,3,axis=0)
print(data)
print(dt2)
print(dt3)

[[18 22 89  3 28]
 [42 54 99 65 97]
 [ 6  4 95 70 57]
 [12 84 29 58 86]]
[[74 34 79 37 88]
 [52 96 15 45 62]
 [ 3  7 26 90 19]]
[[17 25 93 89 67]
 [ 7  5 94 16 95]
 [83 95 33 46 10]]
