## ndarray Arithmetic Operators and Mathematical function

In [2]:
import numpy as np 

x = np.array([10,20,30,40,50])
y = np.array([1,2,3,4,5])

z = x + y
print(z)

z = x - y
print(z)

z = x * y
print(z)

z = x / y
print(z)

z = x % y
print(z)

z = x ** y
print(z)

z = x // y
print(z)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[0 0 0 0 0]
[       10       400     27000   2560000 312500000]
[10 10 10 10 10]


In [11]:
print("sin")
sin = np.sin(x)
print(sin)

print("cos")
cos = np.cos(x)
print(cos)

print("tan")
tan = np.tan(x)
print(tan)

print("sqrt")
sqrt = np.sqrt(x)
print(sqrt)

print("log")
log = np.log(x)
print(log)

print("deg_conv")
deg_conv = np.deg2rad(x)
print(deg_conv)

print("rad_conv")
rad_conv = np.rad2deg(x)
print(rad_conv)

print("exp")
exp = np.exp(x)
print(exp)

print("log10")
log10 = np.log10(x)
print(log10)

print("sum")
sum = np.sum(x)
print(sum)

print("mean")
mean = np.mean(x)
print(mean)

print("median")
median = np.median(x)
print(median)

print("std")
std = np.std(x)
print(std)

print("var")
var = np.var(x)
print(var)

print("max")
max = np.max(x)
print(max)

print("min")
min = np.min(x)
print(min)

print("range")
range = np.max(x) - np.min(x)
print(range)

sin
[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
cos
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
tan
[ 0.64836083  2.23716094 -6.4053312  -1.11721493 -0.27190061]
sqrt
[3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
log
[2.30258509 2.99573227 3.40119738 3.68887945 3.91202301]
deg_conv
[0.17453293 0.34906585 0.52359878 0.6981317  0.87266463]
rad_conv
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052 2864.78897565]
exp
[2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17
 5.18470553e+21]
log10
[1.         1.30103    1.47712125 1.60205999 1.69897   ]
sum
150
mean
30.0
median
30.0
std
14.142135623730951
var
200.0
max
50
min
10
range
40
