## Numpy Broadcasting

In [10]:
import numpy as np 

x = np.array([10,20,30,40,50])
y = np.array([1,2,3,4,5])

print(x)
print(y)

[10 20 30 40 50]
[1 2 3 4 5]


In [11]:
sqrt = x ** 2 
print(sqrt)

sum = x + 2 
print(sum)

sub = x - 2 
print(sub)

mul = x * 2 
print(mul)

div = x / 2 
print(div)

mod = x % 2 

[ 100  400  900 1600 2500]
[12 22 32 42 52]
[ 8 18 28 38 48]
[ 20  40  60  80 100]
[ 5. 10. 15. 20. 25.]


In [12]:
d2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

vector = np.array([1,2,3,4,5])

sum = d2 + vector
print(sum)

sub = d2 - vector
print(sub)

mul = d2 * vector
print(mul)

div = d2 / vector
print(div)

[[ 2  4  6  8 10]
 [ 7  9 11 13 15]]
[[0 0 0 0 0]
 [5 5 5 5 5]]
[[ 1  4  9 16 25]
 [ 6 14 24 36 50]]
[[1.         1.         1.         1.         1.        ]
 [6.         3.5        2.66666667 2.25       2.        ]]
