## Numpy Logical Functions

In [1]:
import numpy as np 

x = np.array([10,20,30,40,50])
y = np.array([1,20,3,47,5])

print(x)
print(y)

print(x > y)
print(x < y)
print(x == y)
print(x != y)
print(x >= y)
print(x <= y)

[10 20 30 40 50]
[ 1 20  3 47  5]
[ True False  True False  True]
[False False False  True False]
[False  True False False False]
[ True False  True  True  True]
[ True  True  True False  True]
[False  True False  True False]


In [2]:
equal  = x == y
print(np.all(equal))
print(np.any(equal))


not_equal = x != y
print(np.all(not_equal))
print(np.any(not_equal))

greater_than = x > y
print(np.all(greater_than))
print(np.any(greater_than))

less_than = x < y
print(np.all(less_than))
print(np.any(less_than))

greater_than_or_equal = x >= y
print(np.all(greater_than_or_equal))
print(np.any(greater_than_or_equal))

False
True
False
True
False
True
False
True
False
True


## Sorting 

In [3]:

x = np.array([100,20,30,40,10])

z = x.copy()
print(z)
# inplace sorting 
z.sort()
print(z)
print(x)


# copy sorting 
sort_array = np.sort(x)
print(sort_array)
print(x)

[100  20  30  40  10]
[ 10  20  30  40 100]
[100  20  30  40  10]
[ 10  20  30  40 100]
[100  20  30  40  10]


In [4]:
x = np.array([[100,20,350,40,10],[130,120,110,100,90]])


# copy sorting 
sort_array = np.sort(x,axis=0)
print(sort_array)
print(x)

print("--------------------------------")
# copy sorting 
sort_array = np.sort(x,axis=1)
print(sort_array)
print(x)

[[100  20 110  40  10]
 [130 120 350 100  90]]
[[100  20 350  40  10]
 [130 120 110 100  90]]
--------------------------------
[[ 10  20  40 100 350]
 [ 90 100 110 120 130]]
[[100  20 350  40  10]
 [130 120 110 100  90]]


## ndarray Searching

In [5]:
x = np.array([100,20,30,40,10])

In [6]:
index = np.where(x>=30)
print(index)

(array([0, 2, 3]),)


In [7]:
index = np.where(x>=30,x,0)
print(index)

[100   0  30  40   0]


In [8]:
x = np.array([[100,20,350,40,10],[440,120,110,100,90]])

index = np.where(x==100)
print(index)

index = np.where(x>=100,x,0)
print(index)

max_v_index = np.argmax(x)
print(max_v_index)

min_v_index = np.argmin(x)
print(min_v_index)

(array([0, 1]), array([0, 3]))
[[100   0 350   0   0]
 [440 120 110 100   0]]
5
4


## Counting 

In [11]:
arr = np.random.randint(1,100,size=(10,5))
print(arr)

[[67 54 55 67 64]
 [84 59 13 48 85]
 [53 74 83 29 34]
 [47 29 57 32 22]
 [85  6 84 71 43]
 [14 73 51 18 41]
 [12 57 97 18 84]
 [13 30 65 42 50]
 [17 88 62 27 10]
 [28 84  4  9 61]]


In [12]:
val_great_60 = np.count_nonzero(arr > 60)
print(val_great_60)

18


In [14]:
unique,count = np.unique(arr,return_counts=True)
print(unique)
print(count)

[ 4  6  9 10 12 13 14 17 18 22 27 28 29 30 32 34 41 42 43 47 48 50 51 53
 54 55 57 59 61 62 64 65 67 71 73 74 83 84 85 88 97]
[1 1 1 1 1 2 1 1 2 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 2 1 1 1 1
 4 2 1 1]
