## Statistical function

In [41]:
import numpy as np

df = np.genfromtxt('student_dataset.csv',delimiter=',',skip_header=1)
# remove the first and second column
df = df[:,2:]
print(df)

[[85. 92. 88. 10.  6.]
 [78. 85. 82.  9.  4.]
 [92. 89. 95. 11.  7.]
 [76. 81. 79. 10.  3.]
 [88. 94. 91. 12.  5.]
 [83. 87. 85.  9.  4.]
 [95. 98. 93. 11.  8.]
 [71. 75. 73. 10.  2.]
 [89. 91. 87. 12.  6.]
 [82. 86. 84.  9.  4.]
 [90. 93. 89. 11.  6.]
 [77. 80. 78. 10.  3.]
 [86. 88. 85. 12.  5.]
 [94. 96. 92.  9.  7.]
 [81. 84. 83. 11.  4.]
 [79. 82. 80. 10.  3.]
 [87. 90. 86. 12.  5.]
 [93. 95. 91.  9.  6.]
 [75. 78. 76. 11.  2.]
 [88. 92. 89. 10.  5.]
 [91. 94. 88. 12.  6.]
 [84. 87. 85.  9.  4.]
 [86. 89. 87. 11.  5.]
 [92. 95. 93. 10.  7.]
 [78. 81. 79. 12.  3.]
 [89. 92. 90.  9.  5.]
 [85. 88. 86. 11.  4.]
 [90. 93. 91. 10.  6.]
 [76. 79. 77. 12.  2.]
 [87. 90. 88.  9.  5.]
 [83. 86. 84. 11.  4.]
 [94. 97. 95. 10.  7.]
 [80. 83. 81. 12.  3.]
 [88. 91. 89.  9.  5.]
 [91. 94. 92. 11.  6.]
 [77. 80. 78. 10.  2.]
 [86. 89. 87. 12.  5.]
 [89. 92. 90.  9.  5.]
 [84. 87. 85. 11.  4.]
 [92. 95. 93. 10.  6.]
 [79. 82. 80. 12.  3.]
 [87. 90. 88.  9.  5.]
 [85. 88. 86. 11.  4.]
 [90. 93. 9

In [42]:
# statistical function

from numpy import median


math_marks = df[:,0]
science_marks = df[:,1]
english_marks = df[:,2]
grade_level = df[:,3]
study_hour = df[:,4]

print(math_marks)
print(science_marks)
print(english_marks)
print(grade_level)
print(study_hour)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

mean_math_marks = np.mean(math_marks)
print(mean_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

std_math_marks = np.std(math_marks)
print(std_math_marks)


corr_math_marks = np.corrcoef(grade_level,study_hour)
print(corr_math_marks)

[85. 78. 92. 76. 88. 83. 95. 71. 89. 82. 90. 77. 86. 94. 81. 79. 87. 93.
 75. 88. 91. 84. 86. 92. 78. 89. 85. 90. 76. 87. 83. 94. 80. 88. 91. 77.
 86. 89. 84. 92. 79. 87. 85. 90. 76. 88. 93. 81. 86. 89. 78. 87. 91. 84.
 88. 92. 77. 85. 90. 83. 87. 89. 76. 88. 93. 80. 86. 91. 78. 87. 84. 89.
 92. 77. 85. 88. 90. 79. 86. 93. 75. 87. 91. 82. 88. 89. 76. 85. 92. 80.
 87. 90. 78. 86. 91. 83. 88. 89. 77. 85.]
[92. 85. 89. 81. 94. 87. 98. 75. 91. 86. 93. 80. 88. 96. 84. 82. 90. 95.
 78. 92. 94. 87. 89. 95. 81. 92. 88. 93. 79. 90. 86. 97. 83. 91. 94. 80.
 89. 92. 87. 95. 82. 90. 88. 93. 79. 91. 96. 84. 89. 92. 81. 90. 94. 87.
 91. 95. 80. 88. 93. 86. 90. 92. 79. 91. 96. 83. 89. 94. 81. 90. 87. 92.
 95. 80. 88. 91. 93. 82. 89. 96. 78. 90. 94. 85. 91. 92. 79. 88. 95. 83.
 90. 93. 81. 89. 94. 86. 91. 92. 80. 88.]
[88. 82. 95. 79. 91. 85. 93. 73. 87. 84. 89. 78. 85. 92. 83. 80. 86. 91.
 76. 89. 88. 85. 87. 93. 79. 90. 86. 91. 77. 88. 84. 95. 81. 89. 92. 78.
 87. 90. 85. 93. 80. 88. 86. 91. 77. 89.