## Advance Indexing

In [1]:
import numpy as np
arr = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20],[21,22,23,24,25,26,27,28,29,30]])

print(arr)


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]


In [12]:
# copy and view

arr = np.array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
    ])

print(arr)

arr2 = arr[0:2,0:2]
arr2[0,0] = 100
print(arr2)
print(arr)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
[[100   2]
 [ 11  12]]
[[100   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]]


In [31]:
# Advance Indexing

arr = np.array([1,2,3,4,5,6,7,8,9,10])

values = arr[[0,1,2,3]] 
print("Accessing rows 0, 1, 2, 3:")
print(values)

values2 = arr[[1,2]]
print("Accessing rows 1, 2:")
print(values2)

Accessing rows 0, 1, 2, 3:
[1 2 3 4]
Accessing rows 1, 2:
[2 3]


In [52]:
# Advance Indexing

arr = np.array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
    ])

values = arr[[0,1,2],[0,0,0]]
print(values)


values = arr[[0,1,2],[1,1,1]]
print(values)

[ 1 11 21]
[ 2 12 22]


In [58]:
# Iteration
arr = np.array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
    ])

# for row in arr:
#     for col in row:
#         print(col, end=" ")
#     print()

# way 2:
for row in np.nditer(arr):
    print(row, end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 

In [60]:
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [61]:
arr = np.array([1, 2.5, 3])
print(arr.dtype)

float64


In [62]:
print(np.linspace(0,10,5))


[ 0.   2.5  5.   7.5 10. ]


In [63]:
arr = np.full((2,2), np.inf)
print(arr)

[[inf inf]
 [inf inf]]


In [64]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[:,1])

[20 50]


In [69]:
arr = np.random.rand(2,3)
print(arr)

[[0.96435185 0.05257241 0.72677534]
 [0.28881754 0.7167918  0.51959286]]


In [70]:
arr = np.array([1,2,3,4,5])
arr[1:4] = 0
print(arr)

[1 0 0 0 5]
