## creating diagonal matrix

In [12]:
## creating diagonal matrix
import numpy as np
diagonal_matrix = np.diag([1,2,3,4])
print(diagonal_matrix)
print(diagonal_matrix.shape)
print(diagonal_matrix.ndim)
print(diagonal_matrix.size)
print(diagonal_matrix.dtype)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)
2
16
int64


## identity matrix

In [17]:
# creating identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)
print(identity_matrix.shape)
print(identity_matrix.ndim)
print(identity_matrix.size)
print(identity_matrix.dtype)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)
2
9
float64


In [18]:

identity_matrix = np.eye(3,4)
print(identity_matrix)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [19]:

identity_matrix = np.eye(3,4,-1)
print(identity_matrix)


[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [20]:

identity_matrix = np.eye(3,4,1)
print(identity_matrix)


[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
