## ndarray Indexing and Slicing

In [6]:
# indexing and slicing

import numpy as np
arr = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])

print(arr)


[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [8]:
arr = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])

print(arr[0])
print(arr[1])

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


In [10]:
arr = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])

print(arr[0][0], arr[0][1], arr[0][2], arr[0][3], arr[0][4], arr[0][5], arr[0][6], arr[0][7], arr[0][8], arr[0][9])
print(arr[1][0], arr[1][1], arr[1][2], arr[1][3], arr[1][4], arr[1][5], arr[1][6], arr[1][7], arr[1][8], arr[1][9])

1 2 3 4 5 6 7 8 9 10
11 12 13 14 15 16 17 18 19 20


In [36]:
# slicing 

# arr [row_start:row_end, column_start:column_end]
arr = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])

print(arr[0:1,])
print()
print(arr[1:2,])
print()
print(arr[0:2,])
print()
print(arr[0:2, 0:2])
print()
print(arr[1:2, 1:2])
print()
print(arr[0:10, 0:10:2])

[[ 1  2  3  4  5  6  7  8  9 10]]

[[11 12 13 14 15 16 17 18 19 20]]

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

[[ 1  2]
 [11 12]]

[[12]]

[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [49]:
arr = np.array([
    [1,2,3,4,5,6,7,8,9,10],
    [11,12,13,14,15,16,17,18,19,20],
    [21,22,23,24,25,26,27,28,29,30]
    ])

# print rows 
print(arr[0:1,])
print()
print(arr[1:2,])
print()
print(arr[2:3,])
print()


# print columns
print(arr[:,0:1])
print()
print(arr[:,1:2])
print()
print(arr[:,2:3])

[[ 1  2  3  4  5  6  7  8  9 10]]

[[11 12 13 14 15 16 17 18 19 20]]

[[21 22 23 24 25 26 27 28 29 30]]

[[ 1]
 [11]
 [21]]

[[ 2]
 [12]
 [22]]

[[ 3]
 [13]
 [23]]
