## ndarray creation from scratch

In [100]:
# np.zeros 
import numpy as np

arr = np.zeros((2,3), dtype=np.int64)

print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0 0 0]
 [0 0 0]]
int64
(2, 3)
2
6


In [101]:
arr = np.zeros_like(arr)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0 0 0]
 [0 0 0]]
int64
(2, 3)
2
6


In [102]:
arr = np.ones((3,2,3), dtype=np.int64)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
int64
(3, 2, 3)
3
18


In [103]:
arr = np.ones_like(arr)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
int64
(3, 2, 3)
3
18


In [104]:
arr = np.empty((4,3), dtype=np.int8)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[-19 103 -15]
 [ 48   0   0]
 [  0   0   0]
 [  0   0   0]]
int8
(4, 3)
2
12


In [105]:
arr = np.empty_like(arr)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
int8
(4, 3)
2
12


In [106]:
arr = np.full((4,3),True)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
bool
(4, 3)
2
12


## ndarray generation with random values

In [107]:
# np.random,rand(shape)

arr = np.random.rand(2,3)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.91307739 0.96160794 0.78537656]
 [0.75114623 0.41865851 0.67299316]]
float64
(2, 3)
2
6


In [108]:
# np.random,randint(start , end (shape))

arr = np.random.randint(1,11,(2,3))
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 5 3]
 [1 3 4]]
int64
(2, 3)
2
6


In [109]:
# np.random,randint(start , end (shape))

arr = np.random.uniform(1,11,(2,3))
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[ 5.63113745  2.54528958 10.80883702]
 [10.37746991  3.29342169  6.97570934]]
float64
(2, 3)
2
6


## ndarray creation from range

In [115]:
# np.arange(first,end,step)

arr = np.arange(1,10,1).reshape(3,3)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
int64
(3, 3)
2
9


In [124]:
# np.linespace()

arr = np.linspace(1, 10, 15)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]
float64
(15,)
1
15


In [130]:
# np.logspace()

arr = np.logspace(0, 4, 6, base=2)
print(arr)
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]
float64
(6,)
1
6
