In [1]:
# Intro to Numpy\

# continuous 
# same type (homogenous)

# opetations 
# vectorization 

# cpu - > simd single instructions multiple data 



 ## Ndarray and its attributes

In [2]:
arr = [1,2,3]
print(arr*5)

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [3]:
arr = [1,2,3]

arr = [x*5 for x in arr]
print(arr)

[5, 10, 15]


In [4]:
import numpy as np 

arr1 = np.array([1,2,3])
arr1 = arr1 * 5 
print(arr1)

print()
arr2 = np.array([arr1*1,arr1*2,arr1*3])
print(arr2)

[ 5 10 15]

[[ 5 10 15]
 [10 20 30]
 [15 30 45]]


In [5]:
# ND array

import numpy as np 

arr1 = np.array([1,2,3,4,5,6]) # 1D array
arr2 = np.array([
    [1,2,3,4,5,6],
    [7,8,9,10,11,12]
]) #2D array

arr3 = np.array([
    [
    [1,2,3,4,5,6],
    [7,8,9,10,11,12]
],
    [
    [1,2,3,4,5,6],
    [7,8,9,10,11,12]
],
    [
    [1,2,3,4,5,6],
    [7,8,9,10,11,12]
],
])

print(type(arr1))
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


<class 'numpy.ndarray'>
1
2
3


In [6]:
# array attributes 

# dimension 
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

print()
# shape 
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

print()
# dtype 
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

print()
# size 
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3

(6,)
(2, 6)
(3, 2, 6)

int64
int64
int64

6
12
36
